version: '3.8'

services:
  hrms-db:
    image: postgres:15-alpine
    container_name: hrms-postgres
    restart: always
    environment:
      POSTGRES_DB: HRMS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - hrms-pgdata:/var/lib/postgresql/data

volumes:
  hrms-pgdata:
