ALTER TABLE resumes ADD COLUMN IF NOT EXISTS cv_file_path VARCHAR(255);
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS cv_file_name VARCHAR(255);
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS cv_upload_date TIMESTAMP;
